# make_modern_font.py -- generate fonts/modern.py for Ripos: a 16px
# monospace ASCII glyph atlas rasterized from a modern system TTF
# (Consolas by default) at build time, so the OS itself carries no font
# files.  Glyphs are 1-bit (thresholded after 2x rendering + LANCZOS
# downscale) so text.py's fast row-slice paint path applies -- thinner,
# smoother strokes AND faster rendering than the old 2x-scaled 8x8 font.
#
# Usage (host, from the workspace root):  py -3 os/target/make_modern_font.py
#
# Output: os/kernel/initramfs_extra/fonts/modern.py
#   FONT     -- the source font name
#   BASELINE -- baseline row within the 16px cell
#   GLYPHS   -- { cp: (advance, ink_width, [16 row bitmaps]) }
#               row bitmap: 16 bits, MSB = leftmost column

import os

FONT_PATH = "C:/Windows/Fonts/consola.ttf"
FONT_NAME = "Consolas"
OUT = os.path.join("os", "kernel", "initramfs_extra", "fonts", "modern.py")

LINE_H = 16          # target line height (matches text.LINE_H)
BASELINE = 12        # baseline row in the 16px cell
CELL_W = 16          # max cell width (CJK width; Latin is narrower)
RENDER = 2           # render at 2x then downscale (smoother strokes)

from PIL import Image, ImageFont, ImageDraw

font = ImageFont.truetype(FONT_PATH, 16 * RENDER)
asc, desc = font.getmetrics()
print("font metrics at %dpx: ascent=%d descent=%d" % (16 * RENDER, asc, desc))


def rasterize(ch):
    """Render ch at 2x, extract the ink, scale into a 16-row cell with the
    baseline at BASELINE, threshold to 1-bit.  Returns (advance, width, rows)."""
    adv = max(int(round(font.getlength(ch) / RENDER)), 4)
    canvas = Image.new("L", (64, 64), 0)
    ImageDraw.Draw(canvas).text((2, 2), ch, font=font, fill=255)
    bbox = canvas.getbbox()
    if bbox is None:
        return (adv, 0, [0] * LINE_H)
    x0, y0, x1, y1 = bbox
    baseline = 2 + asc          # y of the baseline in the 2x render space
    ink_w = x1 - x0
    ink_h = y1 - y0
    s = 1.0 / RENDER
    # place the ink so the baseline lands on BASELINE
    top = BASELINE - int(round((baseline - y0) * s))
    width = max(1, int(round(ink_w * s)))
    height = max(1, int(round(ink_h * s)))
    im = canvas.crop((x0, y0, x1, y1)).resize(
        (width, height), Image.LANCZOS)
    px = im.load()
    rows = [0] * LINE_H
    for r in range(height):
        bits = 0
        for c in range(width):
            if px[c, r] > 96:    # threshold ~38% -> 1-bit
                bits |= 1 << (CELL_W - 1 - c)
        rr = top + r
        if 0 <= rr < LINE_H:
            rows[rr] |= bits
    return (adv, width, rows)


glyphs = {}
for cp in range(32, 127):
    ch = chr(cp)
    glyphs[cp] = rasterize(ch)

advs = sorted({g[0] for g in glyphs.values()})
print("advances seen: %s" % advs)
for ch in "AgpyI0":
    a, w, rows = glyphs[ord(ch)]
    ink = [r for r in rows if r]
    print("  %r advance=%d ink_width=%d ink_rows=%d..%d" % (
        ch, a, w, rows.index(ink[0]) if ink else -1,
        len(rows) - 1 - rows[::-1].index(ink[-1]) if ink else -1))

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    f.write('"""fonts/modern.py -- 16px monospace ASCII glyph atlas.\n')
    f.write("Generated by os/target/make_modern_font.py from %s.\n" % FONT_NAME)
    f.write("1-bit glyphs (16 bits per row, MSB = leftmost column);\n")
    f.write("(advance, ink_width, [16 row bitmaps]) per code point.\n")
    f.write('"""\n\n')
    f.write("FONT = %r\n" % FONT_NAME)
    f.write("BASELINE = %d\n" % BASELINE)
    f.write("LINE_H = %d\n" % LINE_H)
    f.write("CELL_W = %d\n" % CELL_W)
    f.write("GLYPHS = {\n")
    for cp in range(32, 127):
        adv, w, rows = glyphs[cp]
        f.write("    %d: (%d, %d, [%s]),\n" % (
            cp, adv, w, ", ".join(str(r) for r in rows)))
    f.write("}\n")

print("wrote %s" % OUT)
print("size: %d bytes" % os.path.getsize(OUT))
